### ISSUE TITLE
Not able to login

### ISSUE THREAD

**Issue by anborg** [cortezaproject/corteza-webapp-one#54]
I'm trying to compile and run in windows (no docker allowed). 

I was able to compile and run corteza-server, however the UI seem to be in 'developer mode', not able to login. Is this the right repo for UI? what admin uid/pwd should I use?
Thank you

![image](https://user-images.githubusercontent.com/56970398/108614330-8ad78b80-73c7-11eb-999b-2ff06346a117.png)

**Comment by tjerman** [comment]
@anborg These are all of the repos that you need to compile in order to provide the full functionality (make sure you're using the same branch on each one of them; 2020.12.x is currently the latest stable). Keep in mind that the next version (2021.3) is about to release sometime next month.

* https://github.com/cortezaproject/corteza-server -- backend
* https://github.com/cortezaproject/corteza-server-corredor -- automation script execution

* https://github.com/cortezaproject/corteza-webapp-auth -- authentication
* https://github.com/cortezaproject/corteza-webapp-admin -- administration
* https://github.com/cortezaproject/corteza-webapp-compose -- Corteza Low-code
* https://github.com/cortezaproject/corteza-webapp-one -- Corteza unify
* https://github.com/cortezaproject/corteza-webapp-messaging -- Corteza messaging

The screen you're looking at shows when you're running on a local environment without the webapp-auth application -- the web app redirects to a login page residing in that web app.

What I would suggest you do is compile and run all of the above-mentioned things (you can refer to the package.json, Makefile, Docker, and docker-compose.yaml files for that).

How I do this when developing (I'm on Ubuntu but it shouldn't differ for you):
* `make realize;` inside the server repo to run the server (make sure all of the configs are there).
* `yarn serve --port $PORT_HERE;` inside a web app to run it.

To build them (I think) you would use `make build` and `yarn build`; move the sources to the server (if not already there) and the rest is standard dev-ops.

I hope this gives you a bit more context to help you out.

**Comment by anborg** [comment]
@tjerman , Thank you very much, for the detailed information. 

>(2021.3) is about to release sometime next month

That's a one year difference! I'll experiment with compiling, but the real compile, I'll try to do with 2021.3


>the sources to the server (if not already there) and the **rest is standard dev-ops**.

You make it feel simple, I'll give it a try :).  Would be nice if there is a script that can just download the repos in current dir and compile and run in dev mode.

**Comment by zmija** [comment]
hi @anborg, I'll close this issue for now. If you need anything, you know where to find us. Cheers!
